services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  authservice:
    container_name: authservice

    build:
      context: .
      dockerfile: src/AuthService/Dockerfile

    ports:
      - "7144:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/app/data/auth.db
      RabbitMQ__HostName: rabbitmq
      Services__ProductService: http://productservice:8080
      Services__InventoryService: http://inventoryservice:8080
      Services__PaymentService: http://paymentservice:8080
      Services__AuthService: http://authservice:8080
      Services__OrderService: http://orderservice:8080

    volumes:
      - auth-data:/app/data

    depends_on:
      - rabbitmq
      - productservice
      - inventoryservice
      - orderservice

  productservice:
    container_name: productservice

    build:
      context: .
      dockerfile: src/ProductService/Dockerfile

    ports:
      - "7165:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/app/data/products.db

      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest

    volumes:
      - product-data:/app/data

    depends_on:
      - rabbitmq

  inventoryservice:
    container_name: inventoryservice

    build:
      context: .
      dockerfile: src/InventoryService/Dockerfile

    ports:
      - "7248:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/app/data/inventory.db

      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest

    volumes:
      - inventory-data:/app/data

    depends_on:
      - rabbitmq

  orderservice:
    container_name: orderservice

    build:
      context: .
      dockerfile: src/OrderService/Dockerfile

    ports:
      - "7199:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/app/data/orders.db
      Services__InventoryService: http://inventoryservice:8080
      Services__ProductService: http://productservice:8080

      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest

    volumes:
      - order-data:/app/data

    depends_on:
      - rabbitmq

  paymentservice:
      container_name: paymentservice

      build:
        context: .
        dockerfile: src/PaymentService/Dockerfile

      ports:
        - "7068:8080"

      environment:
        ASPNETCORE_ENVIRONMENT: Development
        ConnectionStrings__DefaultConnection: Data Source=/app/data/payments.db
        Services__AuthService: http://authservice:8080

        RabbitMQ__HostName: rabbitmq
        RabbitMQ__Port: "5672"
        RabbitMQ__UserName: guest
        RabbitMQ__Password: guest

      volumes:
        - payment-data:/app/data

      depends_on:
        - rabbitmq

volumes:
  auth-data:
  product-data:
  inventory-data:
  order-data:
  payment-data: